class CountryData {
  final String name;
  final String code;
  final String flag;
  final String currencyCode;
  final String currencyName;
  final String greeting;
  final String funFact;
  final String emojiScene;

  CountryData({
    required this.name,
    required this.code,
    required this.flag,
    required this.currencyCode,
    required this.currencyName,
    required this.greeting,
    required this.funFact,
    required this.emojiScene,
  });
}

class CountriesData {
  static final List<CountryData> countries = [
    CountryData(
      name: 'South Africa',
      code: 'ZA',
      flag: '🇿🇦',
      currencyCode: 'ZAR',
      currencyName: 'South African Rand',
      greeting: 'Sawubona!',
      funFact: 'Home to Table Mountain & safari adventures!',
      emojiScene: '🦁🌍🏔️',
    ),
    CountryData(
      name: 'Egypt',
      code: 'EG',
      flag: '🇪🇬',
      currencyCode: 'EGP',
      currencyName: 'Egyptian Pound',
      greeting: 'Marhaban!',
      funFact: 'The pyramids are over 4,500 years old!',
      emojiScene: '🏜️🐪🔺',
    ),
    CountryData(
      name: 'Tanzania',
      code: 'TZ',
      flag: '🇹🇿',
      currencyCode: 'TZS',
      currencyName: 'Tanzanian Shilling',
      greeting: 'Jambo!',
      funFact: 'Home to Mount Kilimanjaro & Serengeti!',
      emojiScene: '🏔️🦒🌅',
    ),
    CountryData(
      name: 'Rwanda',
      code: 'RW',
      flag: '🇷🇼',
      currencyCode: 'RWF',
      currencyName: 'Rwandan Franc',
      greeting: 'Muraho!',
      funFact: 'The land of a thousand hills & mountain gorillas!',
      emojiScene: '🦍🌄🌿',
    ),
    CountryData(
      name: 'Kenya',
      code: 'KE',
      flag: '🇰🇪',
      currencyCode: 'KES',
      currencyName: 'Kenyan Shilling',
      greeting: 'Jambo!',
      funFact: 'Witness the Great Migration in Maasai Mara!',
      emojiScene: '🦒🌅🦓',
    ),
    CountryData(
      name: 'Morocco',
      code: 'MA',
      flag: '🇲🇦',
      currencyCode: 'MAD',
      currencyName: 'Moroccan Dirham',
      greeting: 'Salam!',
      funFact: 'Explore vibrant souks & blue Chefchaouen!',
      emojiScene: '🕌🐫🎨',
    ),
    CountryData(
      name: 'United States',
      code: 'US',
      flag: '🇺🇸',
      currencyCode: 'USD',
      currencyName: 'US Dollar',
      greeting: 'Hey there!',
      funFact: 'From NYC skyscrapers to Grand Canyon!',
      emojiScene: '🗽🌉🏙️',
    ),
    CountryData(
      name: 'United Kingdom',
      code: 'GB',
      flag: '🇬🇧',
      currencyCode: 'GBP',
      currencyName: 'British Pound',
      greeting: 'Hello!',
      funFact: 'Tea time at 4pm is a cherished tradition!',
      emojiScene: '🫖👑🏰',
    ),
    CountryData(
      name: 'France',
      code: 'FR',
      flag: '🇫🇷',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Bonjour!',
      funFact: 'Home to the Eiffel Tower and finest cuisine!',
      emojiScene: '🗼🥐☕',
    ),
    CountryData(
      name: 'Germany',
      code: 'DE',
      flag: '🇩🇪',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Guten Tag!',
      funFact: 'Over 1,500 kinds of beer and 20,000 castles!',
      emojiScene: '🏰🍺🥨',
    ),
    CountryData(
      name: 'Italy',
      code: 'IT',
      flag: '🇮🇹',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Ciao!',
      funFact: 'The Colosseum could hold 50,000 spectators!',
      emojiScene: '🍕🏛️🍝',
    ),
    CountryData(
      name: 'Spain',
      code: 'ES',
      flag: '🇪🇸',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Hola!',
      funFact: 'Birthplace of flamenco & siesta culture!',
      emojiScene: '💃🌞🥘',
    ),
    CountryData(
      name: 'Japan',
      code: 'JP',
      flag: '🇯🇵',
      currencyCode: 'JPY',
      currencyName: 'Japanese Yen',
      greeting: 'Konnichiwa!',
      funFact: 'Cherry blossoms bloom for just 2 weeks!',
      emojiScene: '🌸🗾🍣',
    ),
    CountryData(
      name: 'China',
      code: 'CN',
      flag: '🇨🇳',
      currencyCode: 'CNY',
      currencyName: 'Chinese Yuan',
      greeting: 'Nǐ hǎo!',
      funFact: 'The Great Wall stretches over 13,000 miles!',
      emojiScene: '🏯🐼🥟',
    ),
    CountryData(
      name: 'Thailand',
      code: 'TH',
      flag: '🇹🇭',
      currencyCode: 'THB',
      currencyName: 'Thai Baht',
      greeting: 'Sawasdee!',
      funFact: 'Land of Smiles with 40,000+ Buddhist temples!',
      emojiScene: '🛕🐘🌴',
    ),
    CountryData(
      name: 'India',
      code: 'IN',
      flag: '🇮🇳',
      currencyCode: 'INR',
      currencyName: 'Indian Rupee',
      greeting: 'Namaste!',
      funFact: 'The Taj Mahal changes color throughout the day!',
      emojiScene: '🕌🐅🪔',
    ),
    CountryData(
      name: 'United Arab Emirates',
      code: 'AE',
      flag: '🇦🇪',
      currencyCode: 'AED',
      currencyName: 'UAE Dirham',
      greeting: 'Marhaba!',
      funFact: 'Burj Khalifa is the world\'s tallest building!',
      emojiScene: '🏙️🏜️🐪',
    ),
    CountryData(
      name: 'Australia',
      code: 'AU',
      flag: '🇦🇺',
      currencyCode: 'AUD',
      currencyName: 'Australian Dollar',
      greeting: 'G\'day!',
      funFact: 'Home to 10,000+ beaches and unique wildlife!',
      emojiScene: '🦘🏖️🪃',
    ),
    CountryData(
      name: 'New Zealand',
      code: 'NZ',
      flag: '🇳🇿',
      currencyCode: 'NZD',
      currencyName: 'New Zealand Dollar',
      greeting: 'Kia ora!',
      funFact: 'Middle Earth comes alive in stunning landscapes!',
      emojiScene: '🏔️🥝🐑',
    ),
    CountryData(
      name: 'Canada',
      code: 'CA',
      flag: '🇨🇦',
      currencyCode: 'CAD',
      currencyName: 'Canadian Dollar',
      greeting: 'Hello / Bonjour!',
      funFact: 'More lakes than the rest of the world combined!',
      emojiScene: '🍁🏔️🦫',
    ),
    CountryData(
      name: 'Brazil',
      code: 'BR',
      flag: '🇧🇷',
      currencyCode: 'BRL',
      currencyName: 'Brazilian Real',
      greeting: 'Olá!',
      funFact: 'Rio Carnival is the world\'s biggest party!',
      emojiScene: '🎊⚽🦜',
    ),
    CountryData(
      name: 'Mexico',
      code: 'MX',
      flag: '🇲🇽',
      currencyCode: 'MXN',
      currencyName: 'Mexican Peso',
      greeting: '¡Hola!',
      funFact: 'Ancient Mayan pyramids & cenote swimming!',
      emojiScene: '🌮🏜️🦎',
    ),
    CountryData(
      name: 'Argentina',
      code: 'AR',
      flag: '🇦🇷',
      currencyCode: 'ARS',
      currencyName: 'Argentine Peso',
      greeting: '¡Hola!',
      funFact: 'Tango birthplace & world-class steak!',
      emojiScene: '💃🥩🍷',
    ),
    CountryData(
      name: 'Turkey',
      code: 'TR',
      flag: '🇹🇷',
      currencyCode: 'TRY',
      currencyName: 'Turkish Lira',
      greeting: 'Merhaba!',
      funFact: 'Istanbul bridges Europe & Asia!',
      emojiScene: '🕌🧿🫖',
    ),
    CountryData(
      name: 'Greece',
      code: 'GR',
      flag: '🇬🇷',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Yassas!',
      funFact: 'Over 6,000 islands with stunning blue waters!',
      emojiScene: '🏛️🫒🌊',
    ),
    CountryData(
      name: 'Portugal',
      code: 'PT',
      flag: '🇵🇹',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Olá!',
      funFact: 'Cork capital & birthplace of Port wine!',
      emojiScene: '🍷🌊🏰',
    ),
    CountryData(
      name: 'Netherlands',
      code: 'NL',
      flag: '🇳🇱',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Hallo!',
      funFact: 'More bicycles than people!',
      emojiScene: '🚲🌷🏘️',
    ),
    CountryData(
      name: 'Switzerland',
      code: 'CH',
      flag: '🇨🇭',
      currencyCode: 'CHF',
      currencyName: 'Swiss Franc',
      greeting: 'Grüezi!',
      funFact: 'Chocolates, watches & Alpine perfection!',
      emojiScene: '⛷️🍫⌚',
    ),
    CountryData(
      name: 'Sweden',
      code: 'SE',
      flag: '🇸🇪',
      currencyCode: 'SEK',
      currencyName: 'Swedish Krona',
      greeting: 'Hej!',
      funFact: 'Midnight sun in summer, Northern Lights in winter!',
      emojiScene: '🌌❄️🦌',
    ),
    CountryData(
      name: 'Norway',
      code: 'NO',
      flag: '🇳🇴',
      currencyCode: 'NOK',
      currencyName: 'Norwegian Krone',
      greeting: 'Hei!',
      funFact: 'Breathtaking fjords & Viking heritage!',
      emojiScene: '🛶🏔️🌊',
    ),
    CountryData(
      name: 'Denmark',
      code: 'DK',
      flag: '🇩🇰',
      currencyCode: 'DKK',
      currencyName: 'Danish Krone',
      greeting: 'Hej!',
      funFact: 'Happiest country & home of LEGO!',
      emojiScene: '🧱🚲🏰',
    ),
    CountryData(
      name: 'Singapore',
      code: 'SG',
      flag: '🇸🇬',
      currencyCode: 'SGD',
      currencyName: 'Singapore Dollar',
      greeting: 'Hello!',
      funFact: 'A garden city with futuristic architecture!',
      emojiScene: '🏙️🌳🦁',
    ),
    CountryData(
      name: 'Malaysia',
      code: 'MY',
      flag: '🇲🇾',
      currencyCode: 'MYR',
      currencyName: 'Malaysian Ringgit',
      greeting: 'Selamat datang!',
      funFact: 'Petronas Towers were world\'s tallest until 2004!',
      emojiScene: '🏙️🌴🦧',
    ),
    CountryData(
      name: 'Indonesia',
      code: 'ID',
      flag: '🇮🇩',
      currencyCode: 'IDR',
      currencyName: 'Indonesian Rupiah',
      greeting: 'Halo!',
      funFact: 'Over 17,000 islands with stunning beaches!',
      emojiScene: '🏝️🌋🦎',
    ),
    CountryData(
      name: 'South Korea',
      code: 'KR',
      flag: '🇰🇷',
      currencyCode: 'KRW',
      currencyName: 'South Korean Won',
      greeting: 'Annyeonghaseyo!',
      funFact: 'K-pop, kimchi & cutting-edge technology!',
      emojiScene: '🎤🥢🏙️',
    ),
    CountryData(
      name: 'Philippines',
      code: 'PH',
      flag: '🇵🇭',
      currencyCode: 'PHP',
      currencyName: 'Philippine Peso',
      greeting: 'Kumusta!',
      funFact: '7,641 islands with world-class diving!',
      emojiScene: '🏝️🤿🥥',
    ),
    CountryData(
      name: 'Vietnam',
      code: 'VN',
      flag: '🇻🇳',
      currencyCode: 'VND',
      currencyName: 'Vietnamese Dong',
      greeting: 'Xin chào!',
      funFact: 'Halong Bay has 1,600 limestone islands!',
      emojiScene: '🛶🍜🏮',
    ),
    // More African Countries
    CountryData(
      name: 'Nigeria',
      code: 'NG',
      flag: '🇳🇬',
      currencyCode: 'NGN',
      currencyName: 'Nigerian Naira',
      greeting: 'Sannu!',
      funFact: 'Africa\'s most populous country with vibrant culture!',
      emojiScene: '🎭🥁🌍',
    ),
    CountryData(
      name: 'Ghana',
      code: 'GH',
      flag: '🇬🇭',
      currencyCode: 'GHS',
      currencyName: 'Ghanaian Cedi',
      greeting: 'Akwaaba!',
      funFact: 'Home to historical slave trade castles!',
      emojiScene: '🏰🥁🌴',
    ),
    CountryData(
      name: 'Ethiopia',
      code: 'ET',
      flag: '🇪🇹',
      currencyCode: 'ETB',
      currencyName: 'Ethiopian Birr',
      greeting: 'Selam!',
      funFact: 'Birthplace of coffee and ancient civilization!',
      emojiScene: '☕🦁⛪',
    ),
    CountryData(
      name: 'Senegal',
      code: 'SN',
      flag: '🇸🇳',
      currencyCode: 'XOF',
      currencyName: 'West African Franc',
      greeting: 'Salaam aleekum!',
      funFact: 'Pink Lake and vibrant music scene!',
      emojiScene: '🌸🥁🌊',
    ),
    CountryData(
      name: 'Uganda',
      code: 'UG',
      flag: '🇺🇬',
      currencyCode: 'UGX',
      currencyName: 'Ugandan Shilling',
      greeting: 'Oli otya!',
      funFact: 'Pearl of Africa with mountain gorillas!',
      emojiScene: '🦍🌄💎',
    ),
    CountryData(
      name: 'Botswana',
      code: 'BW',
      flag: '🇧🇼',
      currencyCode: 'BWP',
      currencyName: 'Botswana Pula',
      greeting: 'Dumela!',
      funFact: 'Okavango Delta & abundant wildlife!',
      emojiScene: '🐘💎🏜️',
    ),
    CountryData(
      name: 'Namibia',
      code: 'NA',
      flag: '🇳🇦',
      currencyCode: 'NAD',
      currencyName: 'Namibian Dollar',
      greeting: 'Hello!',
      funFact: 'Stunning desert landscapes & red dunes!',
      emojiScene: '🏜️🦒🌅',
    ),
    CountryData(
      name: 'Zimbabwe',
      code: 'ZW',
      flag: '🇿🇼',
      currencyCode: 'USD',
      currencyName: 'US Dollar',
      greeting: 'Mhoro!',
      funFact: 'Victoria Falls - the Smoke that Thunders!',
      emojiScene: '🌊🦁🏞️',
    ),
    // More Asian Countries
    CountryData(
      name: 'Cambodia',
      code: 'KH',
      flag: '🇰🇭',
      currencyCode: 'KHR',
      currencyName: 'Cambodian Riel',
      greeting: 'Chomreabsuor!',
      funFact: 'Ancient Angkor Wat temple complex!',
      emojiScene: '🛕🌅🌴',
    ),
    CountryData(
      name: 'Laos',
      code: 'LA',
      flag: '🇱🇦',
      currencyCode: 'LAK',
      currencyName: 'Lao Kip',
      greeting: 'Sabaidee!',
      funFact: 'Land of a Million Elephants!',
      emojiScene: '🐘🛕🌄',
    ),
    CountryData(
      name: 'Myanmar',
      code: 'MM',
      flag: '🇲🇲',
      currencyCode: 'MMK',
      currencyName: 'Myanmar Kyat',
      greeting: 'Mingalarbar!',
      funFact: 'Golden pagodas & ancient temples!',
      emojiScene: '🛕✨🌅',
    ),
    CountryData(
      name: 'Sri Lanka',
      code: 'LK',
      flag: '🇱🇰',
      currencyCode: 'LKR',
      currencyName: 'Sri Lankan Rupee',
      greeting: 'Ayubowan!',
      funFact: 'Island paradise with Ceylon tea!',
      emojiScene: '🏝️☕🐘',
    ),
    CountryData(
      name: 'Nepal',
      code: 'NP',
      flag: '🇳🇵',
      currencyCode: 'NPR',
      currencyName: 'Nepalese Rupee',
      greeting: 'Namaste!',
      funFact: 'Home to Mount Everest & Himalayas!',
      emojiScene: '🏔️🙏⛰️',
    ),
    CountryData(
      name: 'Maldives',
      code: 'MV',
      flag: '🇲🇻',
      currencyCode: 'MVR',
      currencyName: 'Maldivian Rufiyaa',
      greeting: 'Assalaamu alaikum!',
      funFact: 'Tropical paradise with crystal waters!',
      emojiScene: '🏝️🐠🌊',
    ),
    CountryData(
      name: 'Bangladesh',
      code: 'BD',
      flag: '🇧🇩',
      currencyCode: 'BDT',
      currencyName: 'Bangladeshi Taka',
      greeting: 'Nomoshkar!',
      funFact: 'Land of rivers & mangrove forests!',
      emojiScene: '🌊🐯🌿',
    ),
    CountryData(
      name: 'Pakistan',
      code: 'PK',
      flag: '🇵🇰',
      currencyCode: 'PKR',
      currencyName: 'Pakistani Rupee',
      greeting: 'Assalam o Alaikum!',
      funFact: 'K2 & stunning mountain ranges!',
      emojiScene: '🏔️🕌🌟',
    ),
    CountryData(
      name: 'Taiwan',
      code: 'TW',
      flag: '🇹🇼',
      currencyCode: 'TWD',
      currencyName: 'New Taiwan Dollar',
      greeting: 'Nǐ hǎo!',
      funFact: 'Night markets & bubble tea capital!',
      emojiScene: '🧋🏮🌃',
    ),
    CountryData(
      name: 'Hong Kong',
      code: 'HK',
      flag: '🇭🇰',
      currencyCode: 'HKD',
      currencyName: 'Hong Kong Dollar',
      greeting: 'Nei ho!',
      funFact: 'Stunning skyline & dim sum paradise!',
      emojiScene: '🏙️🥟✨',
    ),
    CountryData(
      name: 'Mongolia',
      code: 'MN',
      flag: '🇲🇳',
      currencyCode: 'MNT',
      currencyName: 'Mongolian Tögrög',
      greeting: 'Sain bainuu!',
      funFact: 'Nomadic culture & vast steppes!',
      emojiScene: '🏇🏕️🌾',
    ),
    // Middle Eastern Countries
    CountryData(
      name: 'Saudi Arabia',
      code: 'SA',
      flag: '🇸🇦',
      currencyCode: 'SAR',
      currencyName: 'Saudi Riyal',
      greeting: 'Marhaba!',
      funFact: 'Ancient heritage & modern cities!',
      emojiScene: '🕌🏜️🐪',
    ),
    CountryData(
      name: 'Qatar',
      code: 'QA',
      flag: '🇶🇦',
      currencyCode: 'QAR',
      currencyName: 'Qatari Riyal',
      greeting: 'Marhaba!',
      funFact: 'Modern architecture & desert adventures!',
      emojiScene: '🏙️⚽🏜️',
    ),
    CountryData(
      name: 'Kuwait',
      code: 'KW',
      flag: '🇰🇼',
      currencyCode: 'KWD',
      currencyName: 'Kuwaiti Dinar',
      greeting: 'Marhaba!',
      funFact: 'Rich culture & Arabian Gulf charm!',
      emojiScene: '🏙️🛢️🌊',
    ),
    CountryData(
      name: 'Oman',
      code: 'OM',
      flag: '🇴🇲',
      currencyCode: 'OMR',
      currencyName: 'Omani Rial',
      greeting: 'Marhaba!',
      funFact: 'Ancient forts & stunning wadis!',
      emojiScene: '🏰🏜️🌊',
    ),
    CountryData(
      name: 'Jordan',
      code: 'JO',
      flag: '🇯🇴',
      currencyCode: 'JOD',
      currencyName: 'Jordanian Dinar',
      greeting: 'Marhaba!',
      funFact: 'Petra - the Rose City!',
      emojiScene: '🏛️🏜️🐪',
    ),
    CountryData(
      name: 'Lebanon',
      code: 'LB',
      flag: '🇱🇧',
      currencyCode: 'LBP',
      currencyName: 'Lebanese Pound',
      greeting: 'Marhaba!',
      funFact: 'Ancient Phoenician heritage!',
      emojiScene: '🏛️🌲🍷',
    ),
    CountryData(
      name: 'Israel',
      code: 'IL',
      flag: '🇮🇱',
      currencyCode: 'ILS',
      currencyName: 'Israeli Shekel',
      greeting: 'Shalom!',
      funFact: 'Ancient history meets modern innovation!',
      emojiScene: '🕍🏛️🌊',
    ),
    CountryData(
      name: 'Iran',
      code: 'IR',
      flag: '🇮🇷',
      currencyCode: 'IRR',
      currencyName: 'Iranian Rial',
      greeting: 'Salam!',
      funFact: 'Persian carpets & ancient Persepolis!',
      emojiScene: '🕌🏺🌸',
    ),
    // European Countries
    CountryData(
      name: 'Austria',
      code: 'AT',
      flag: '🇦🇹',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Grüß Gott!',
      funFact: 'Mozart, Alps & stunning palaces!',
      emojiScene: '🎼⛰️🏰',
    ),
    CountryData(
      name: 'Belgium',
      code: 'BE',
      flag: '🇧🇪',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Bonjour / Hallo!',
      funFact: 'Chocolate, waffles & medieval towns!',
      emojiScene: '🍫🧇🏛️',
    ),
    CountryData(
      name: 'Czech Republic',
      code: 'CZ',
      flag: '🇨🇿',
      currencyCode: 'CZK',
      currencyName: 'Czech Koruna',
      greeting: 'Ahoj!',
      funFact: 'Prague - City of a Hundred Spires!',
      emojiScene: '🏰🍺🌉',
    ),
    CountryData(
      name: 'Poland',
      code: 'PL',
      flag: '🇵🇱',
      currencyCode: 'PLN',
      currencyName: 'Polish Złoty',
      greeting: 'Cześć!',
      funFact: 'Medieval castles & pierogi!',
      emojiScene: '🏰🥟❄️',
    ),
    CountryData(
      name: 'Hungary',
      code: 'HU',
      flag: '🇭🇺',
      currencyCode: 'HUF',
      currencyName: 'Hungarian Forint',
      greeting: 'Szia!',
      funFact: 'Budapest - Pearl of the Danube!',
      emojiScene: '🏛️♨️🌉',
    ),
    CountryData(
      name: 'Romania',
      code: 'RO',
      flag: '🇷🇴',
      currencyCode: 'RON',
      currencyName: 'Romanian Leu',
      greeting: 'Bună!',
      funFact: 'Dracula\'s castle & Carpathian Mountains!',
      emojiScene: '🏰🧛🌲',
    ),
    CountryData(
      name: 'Croatia',
      code: 'HR',
      flag: '🇭🇷',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Bok!',
      funFact: 'Stunning Adriatic coast & islands!',
      emojiScene: '🏖️⛵🏛️',
    ),
    CountryData(
      name: 'Iceland',
      code: 'IS',
      flag: '🇮🇸',
      currencyCode: 'ISK',
      currencyName: 'Icelandic Króna',
      greeting: 'Halló!',
      funFact: 'Land of fire & ice with Northern Lights!',
      emojiScene: '🌋❄️🌌',
    ),
    CountryData(
      name: 'Finland',
      code: 'FI',
      flag: '🇫🇮',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Hei!',
      funFact: 'Land of thousands of lakes & saunas!',
      emojiScene: '🏞️🛶❄️',
    ),
    CountryData(
      name: 'Ireland',
      code: 'IE',
      flag: '🇮🇪',
      currencyCode: 'EUR',
      currencyName: 'Euro',
      greeting: 'Dia dhuit!',
      funFact: 'Emerald Isle with Celtic heritage!',
      emojiScene: '🍀🏰🎻',
    ),
    CountryData(
      name: 'Scotland',
      code: 'SC',
      flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
      currencyCode: 'GBP',
      currencyName: 'British Pound',
      greeting: 'Hallo!',
      funFact: 'Whisky, bagpipes & Highland beauty!',
      emojiScene: '🏔️🥃🎵',
    ),
    CountryData(
      name: 'Russia',
      code: 'RU',
      flag: '🇷🇺',
      currencyCode: 'RUB',
      currencyName: 'Russian Ruble',
      greeting: 'Privet!',
      funFact: 'Vast landscapes & iconic architecture!',
      emojiScene: '🏛️❄️🎭',
    ),
    CountryData(
      name: 'Ukraine',
      code: 'UA',
      flag: '🇺🇦',
      currencyCode: 'UAH',
      currencyName: 'Ukrainian Hryvnia',
      greeting: 'Pryvit!',
      funFact: 'Golden domes & rich cultural heritage!',
      emojiScene: '⛪🌻🎨',
    ),
    // Americas
    CountryData(
      name: 'Peru',
      code: 'PE',
      flag: '🇵🇪',
      currencyCode: 'PEN',
      currencyName: 'Peruvian Sol',
      greeting: '¡Hola!',
      funFact: 'Machu Picchu & ancient Inca civilization!',
      emojiScene: '🏔️🦙🏛️',
    ),
    CountryData(
      name: 'Chile',
      code: 'CL',
      flag: '🇨🇱',
      currencyCode: 'CLP',
      currencyName: 'Chilean Peso',
      greeting: '¡Hola!',
      funFact: 'Atacama Desert to Patagonian glaciers!',
      emojiScene: '🏔️🍷🌋',
    ),
    CountryData(
      name: 'Colombia',
      code: 'CO',
      flag: '🇨🇴',
      currencyCode: 'COP',
      currencyName: 'Colombian Peso',
      greeting: '¡Hola!',
      funFact: 'Coffee culture & emerald capital!',
      emojiScene: '☕💚🦜',
    ),
    CountryData(
      name: 'Ecuador',
      code: 'EC',
      flag: '🇪🇨',
      currencyCode: 'USD',
      currencyName: 'US Dollar',
      greeting: '¡Hola!',
      funFact: 'Galápagos Islands & biodiversity!',
      emojiScene: '🐢🌋🏝️',
    ),
    CountryData(
      name: 'Bolivia',
      code: 'BO',
      flag: '🇧🇴',
      currencyCode: 'BOB',
      currencyName: 'Bolivian Boliviano',
      greeting: '¡Hola!',
      funFact: 'Uyuni Salt Flats - mirror of the sky!',
      emojiScene: '🏔️✨🦙',
    ),
    CountryData(
      name: 'Costa Rica',
      code: 'CR',
      flag: '🇨🇷',
      currencyCode: 'CRC',
      currencyName: 'Costa Rican Colón',
      greeting: '¡Hola!',
      funFact: 'Pura vida & incredible biodiversity!',
      emojiScene: '🦥🌴🌋',
    ),
    CountryData(
      name: 'Panama',
      code: 'PA',
      flag: '🇵🇦',
      currencyCode: 'USD',
      currencyName: 'US Dollar',
      greeting: '¡Hola!',
      funFact: 'Panama Canal connects two oceans!',
      emojiScene: '🚢🌊🌴',
    ),
    CountryData(
      name: 'Cuba',
      code: 'CU',
      flag: '🇨🇺',
      currencyCode: 'CUP',
      currencyName: 'Cuban Peso',
      greeting: '¡Hola!',
      funFact: 'Classic cars & salsa rhythms!',
      emojiScene: '🚗💃🎺',
    ),
    CountryData(
      name: 'Jamaica',
      code: 'JM',
      flag: '🇯🇲',
      currencyCode: 'JMD',
      currencyName: 'Jamaican Dollar',
      greeting: 'Wah gwaan!',
      funFact: 'Reggae birthplace & stunning beaches!',
      emojiScene: '🎵🏖️🌴',
    ),
    CountryData(
      name: 'Dominican Republic',
      code: 'DO',
      flag: '🇩🇴',
      currencyCode: 'DOP',
      currencyName: 'Dominican Peso',
      greeting: '¡Hola!',
      funFact: 'Caribbean paradise with merengue!',
      emojiScene: '🏖️💃🥥',
    ),
    CountryData(
      name: 'Uruguay',
      code: 'UY',
      flag: '🇺🇾',
      currencyCode: 'UYU',
      currencyName: 'Uruguayan Peso',
      greeting: '¡Hola!',
      funFact: 'Tango heritage & gaucho culture!',
      emojiScene: '🥩🌊🏖️',
    ),
    CountryData(
      name: 'Venezuela',
      code: 'VE',
      flag: '🇻🇪',
      currencyCode: 'VES',
      currencyName: 'Venezuelan Bolívar',
      greeting: '¡Hola!',
      funFact: 'Angel Falls - world\'s highest waterfall!',
      emojiScene: '🌊🏔️🦜',
    ),
    // Oceania & Pacific
    CountryData(
      name: 'Fiji',
      code: 'FJ',
      flag: '🇫🇯',
      currencyCode: 'FJD',
      currencyName: 'Fijian Dollar',
      greeting: 'Bula!',
      funFact: 'Tropical paradise with 333 islands!',
      emojiScene: '🏝️🌺🌊',
    ),
    CountryData(
      name: 'Samoa',
      code: 'WS',
      flag: '🇼🇸',
      currencyCode: 'WST',
      currencyName: 'Samoan Tālā',
      greeting: 'Talofa!',
      funFact: 'Polynesian culture & pristine beaches!',
      emojiScene: '🏝️🌺🥥',
    ),
    CountryData(
      name: 'Tonga',
      code: 'TO',
      flag: '🇹🇴',
      currencyCode: 'TOP',
      currencyName: 'Tongan Paʻanga',
      greeting: 'Malo e lelei!',
      funFact: 'Pacific kingdom with coral reefs!',
      emojiScene: '🏝️🐠👑',
    ),
  ];

  static List<String> get countryNames =>
      countries.map((c) => c.name).toList();

  static List<String> get currencyCodes =>
      countries.map((c) => c.currencyCode).toSet().toList();

  static CountryData? getCountryByName(String name) {
    try {
      return countries.firstWhere((c) => c.name == name);
    } catch (e) {
      return null;
    }
  }

  static CountryData? getCountryByCode(String code) {
    try {
      return countries.firstWhere((c) => c.code == code);
    } catch (e) {
      return null;
    }
  }

  static List<CountryData> searchCountries(String query) {
    if (query.isEmpty) return countries;
    return countries
        .where((c) =>
            c.name.toLowerCase().contains(query.toLowerCase()) ||
            c.currencyCode.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }
}
